const Config = {
  CAMERA_WIDTH_PX: 650,
  CAMERA_HEIGHT_PX: 620,

  WORLD_WIDTH_PX: 640,
  WORLD_HEIGHT_PX: 615,
  WORLD_WALL_TOP_HEIGHT_PX: 105,
  WORLD_WALL_SIDE_WIDTH_PX: 8,
  WORLD_WALL_TOP_RIGHT_WIDTH_PX: 8,
  WORLD_WALL_TOP_RIGHT_HEIGHT_PX: 39,
  WORLD_PIANO_WIDTH_PX: 352,
  WORLD_PIANO_HEIGHT_PX: 1544,
  WORLD_PIANO_SCALE: 0.1,
  WORLD_FLOWERS_WIDTH_PX: 30,
  WORLD_FLOWERS_HEIGHT_PX: 52,
  WORLD_BOOKCASE_WIDTH_PX: 66,
  WORLD_BOOKCASE_HEIGHT_PX: 69,
  WORLD_BOOKCASE_SCALE: 1.5
};